format_version: 9

pipelines:
  readme-display:
    group: defaultGroup
    materials:
      repo:
        git: https://github.com/gocd/gocd-vault-secret-plugin # Здесь укажите URL вашего git-репозитория
        branch: master                        # Укажите нужную ветку
    stages:
      - readme_stage:
          jobs:
            readme_job:
              tasks:
                - exec:
                    command: powershell
                    arguments:
                      - "-Command"
                      - "Get-Content README.md | Out-Host"
