format_version: 10
pipelines:
  readme_reader:
    group: defaultGroup
    materials:
      my_repo:
        git: https://github.com/gocd/gocd-vault-secret-plugin
        branch: master
    stages:
      - read_stage:
          jobs:
            read_readme:
              tasks:
                - exec:
                    command: "powershell"
                    arguments:
                      - "-Command"
                      - "Get-Content (Join-Path $env:GO_PIPELINE_NAME 'my_repo/README.md') -Encoding UTF8"
                  run_if: passed
